name: Build and Push Custom Images

on:
  push:
    tags:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Parse Tag
        run: |
          echo "LANGUAGE=$(./parse_language.sh ${{ github.ref_name }})" >> "$GITHUB_ENV"
          echo "VERSION=$(./parse_version.sh ${{ github.ref_name }})" >> "$GITHUB_ENV"

      - name: Build and push custom image
        run: |
          printf '%s\n' "$LANGUAGE"
          printf '%s\n' "$VERSION"
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/custom-${{ env.LANGUAGE }}:${{ env.VERSION }} dockerfiles/${{ env.LANGUAGE }}/ --build-arg VERSION=${{ env.VERSION }}

      - name: Push image
        run: |
          printf '%s\n' "$LANGUAGE"
          printf '%s\n' "$VERSION"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/custom-${{ env.LANGUAGE }}:${{ env.VERSION }}
