name: Build and Push Custom Images

on:
  push:
    tags:
    branches-ignore:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Parse Tag
        run: |
          echo "LANGUAGE=$(./parse_language.sh ${{ github.ref_name }})" >> "$GITHUB_ENV"
          echo "VERSION=$(./parse_version.sh ${{ github.ref_name }})" >> "$GITHUB_ENV"

      - name: Build and Push
        run: |
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/custom-${{ env.LANGUAGE }}:${{ env.VERSION }} dockerfiles/${{ env.LANGUAGE }}/ --build-arg VERSION=${{ env.VERSION }} --push
